vscode:
  extensions:
    - bajdzis.vscode-database
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - coenraads.bracket-pair-colorizer-2
    - dbaeumer.vscode-eslint
    - eg2.vscode-npm-script
    - esbenp.prettier-vscode
    - github.vscode-pull-request-github
    - mikestead.dotenv
    - ms-azuretools.vscode-docker
    - pkief.material-icon-theme
    - prisma.prisma
    - prisma.vscode-graphql
    - shan.code-settings-sync
    - shd101wyy.markdown-preview-enhanced
    - sirtori.indenticator
    - yzhang.markdown-all-in-one
    - zhuangtongfa.material-theme
ports:
  - port: 3000
    onOpen: ignore
    visibility: public
  - port: 5432
    onOpen: ignore
    visibility: private
  - port: 5555
    onOpen: ignore
    visibility: private
  - port: 9229
    onOpen: ignore
    visibility: private